source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-soopr-seo-tag"
gem "jekyll-markdown-output"
gem "jekyll-llms-output"
gem "kramdown-parser-gfm"
gem "webrick", "~> 1.7"
