source "https://rubygems.org"

gem "jekyll", "~> 3.9"
gem "jekyll-remote-theme"
gem "jekyll-feed"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-soopr-seo-tag"
gem "jekyll-markdown-output"
gem "jekyll-llms-output"